---
- hosts: [dbservers]
  tasks:
       - name: Check httpd status
         systemd: name=httpd state=started
         register: result
         until: result.stdout.find("active(running)") != -1
         retries: 5
         delay: 5
