---
- hosts: [dbservers]
  tasks:
       - name: Check httpd status
         shell: systemctl status httpd
         register: results
         until: results.stdout.find("active (running)") != -1
         retries: 5
         delay: 5
         become: yes
